### ISSUE TITLE
Can't find "QuerySQL" export when building sql example

### ISSUE THREAD

**Issue by simonerom** [machinefi/w3bstream-wasm-assemblyscript-sdk#4]
<img width="1809" alt="image" src="https://user-images.githubusercontent.com/11096047/232091821-cc8bcb73-c2b4-42ae-b56f-5c7a15c25890.png">

**Comment by DLHTX** [comment]
Hi! Are you using the latest version of @w3bstream/wasm-sdk? The latest version is 0.4.0

https://www.npmjs.com/package/@w3bstream/wasm-sdk
